### ISSUE TITLE
Why does c2-w-b create dirty widgets?

### ISSUE THREAD

**Issue by slyrus** [ritschmaster/caveman2-widgets-bootstrap#2]
I'm seeing a dirty widget call back to my server every 10 seconds when I try to use the widgets and defnav form from the README. Any idea why this would be? Seems like this has the potential for a lot of unnecessary web traffic. At a minimum, I'd like to understand why this is happening.

**Comment by ritschmaster** [comment]
Thank you for your input! I see you play around with it :+1: .

This is again an issue of [caveman2-widgets](https://github.com/ritschmaster/caveman2-widgets). The polling is not needed at all but it is needed to load dirty widgets ASAP. The JavaScript function processDirty()  is called when:
- The user clicks an button
- The user clicks an link
- The user submits a form

But what if something changes without user interaction? That's why there's this polling. If you don't need it, you can deactivate it easily by commenting out the interval call in JavaScript: [see here](https://github.com/ritschmaster/caveman2-widgets/blob/master/static/js/widgets.js#L222)
